version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lumen_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - lumen
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: lumen_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lumen
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: lumen_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx:/etc/nginx/conf.d/
    networks:
      - lumen
    depends_on:
      - app

networks:
  lumen:
    driver: bridge

volumes:
  dbdata: